/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.almacen;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author Nicolás
 */
public class interfaz extends javax.swing.JFrame {

    private String comparacion = "probando";

    public JLabel getAdmin() {
        return admin;
    }

    public void setAdmin(JLabel admin) {
        this.admin = admin;
    }

    public JButton getBotonAdmin() {
        return botonAdmin;
    }

    public void setBotonAdmin(JButton botonAdmin) {
        this.botonAdmin = botonAdmin;
    }

    public JButton getBotonUsuario() {
        return botonUsuario;
    }

    public void setBotonUsuario(JButton botonUsuario) {
        this.botonUsuario = botonUsuario;
    }

    public String getContraseñaAdmin() {
        return String.valueOf(contraseñaAdmin);
    }

    public void setContraseñaAdmin(JPasswordField contraseñaAdmin) {
        this.contraseñaAdmin = contraseñaAdmin;
    }

    public JLabel getFondo() {
        return fondo;
    }

    public void setFondo(JLabel fondo) {
        this.fondo = fondo;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getPerroGafas() {
        return perroGafas;
    }

    public void setPerroGafas(JLabel perroGafas) {
        this.perroGafas = perroGafas;
    }

    public JLabel getUsuario() {
        return usuario;
    }

    public void setUsuario(JLabel usuario) {
        this.usuario = usuario;
    }

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        perroGafas = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        botonUsuario = new javax.swing.JButton();
        botonAdmin = new javax.swing.JButton();
        contraseñaAdmin = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        perroGafas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perro swag.png"))); // NOI18N
        getContentPane().add(perroGafas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 310));

        usuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 170, 80));

        admin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Administrador:");
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        botonUsuario.setBackground(new java.awt.Color(0, 0, 51));
        botonUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuario.setText("Entrar");
        getContentPane().add(botonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 110, 40));

        botonAdmin.setBackground(new java.awt.Color(0, 0, 51));
        botonAdmin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonAdmin.setForeground(new java.awt.Color(255, 255, 255));
        botonAdmin.setText("Entrar");
        botonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminActionPerformed(evt);
            }
        });
        getContentPane().add(botonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 110, 40));

        contraseñaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaAdminActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 210, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminActionPerformed
        char[] contraseña = this.contraseñaAdmin.getPassword();
    }//GEN-LAST:event_botonAdminActionPerformed

    private void contraseñaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    public static void validacion() {
        boolean validar = false;

        if (this.getContraseñaAdmin().equals(comparacion)) { //Nos falla
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton botonAdmin;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JPasswordField contraseñaAdmin;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel perroGafas;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
